name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      # I can't reproduce it 100% of the time yet, but in my local (closed source) repository it occurs every single
      # time. To increase the likelihood we build 5 times.
      run: |
        npm ci
        npm run build
        npm run build
        npm run build
        npm run build
        npm run build
      env:
        CI: true
