name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
        max-simultaneous-builds: [1, 2]

    env:
      MAX_SIMULTANEOUS_BUILDS: ${{matrix.max-simultaneous-builds}}

    name: Build on node ${{matrix.node-version}} with ${{matrix.max-simultaneous-builds}} build(s) simultaneously

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        npm ci
        npm run build
      env:
        CI: true
